import schema from './schema.json'
import { setupSpreadsheet } from './lib'

global.main = () => {
    const spreadsheet = setupSpreadsheet(schema)

    // create data validation rules
    const manuscriptRule = SpreadsheetApp.newDataValidation()
        .requireValueInRange(spreadsheet.getRangeByName('manuscripts__id'))
        .setAllowInvalid(false)
        .setHelpText('Manuscript ID must be listed on Manuscripts sheet.')
        .build()
    const repositoryRule = SpreadsheetApp.newDataValidation()
        .requireValueInRange(spreadsheet.getRangeByName('repositories__name'))
        .setAllowInvalid(false)
        .setHelpText('Repository must be listed on Repositories sheet.')
        .build()
    const incipitRule = SpreadsheetApp.newDataValidation()
        .requireValueInRange(spreadsheet.getRangeByName('canonical_stories__incipit'))
        .setAllowInvalid(false)
        .setHelpText('Incipit must match a Canonical Story.')
        .build()
    const canonicalStoryRule = SpreadsheetApp.newDataValidation()
        .requireValueInRange(spreadsheet.getRangeByName('canonical_stories__macomber_id'))
        .setAllowInvalid(false)
        .setHelpText('Story instance must correspond to a Canonical Story.')
        .build()
    const booleanRule = SpreadsheetApp.newDataValidation()
        .requireCheckbox()
        .setAllowInvalid(false)
        .build()
    
    // apply data validation rules and formulas
    spreadsheet.getSheetByName('Manuscripts')
        .getRange('C2:C')
        .setDataValidation(repositoryRule)
    spreadsheet.getSheetByName('Manuscripts')
        .getRange('D2:D')
        .setDataValidation(repositoryRule)
    spreadsheet.getSheetByName('Canonical Stories')
        .getRange('E2:E')
        .setDataValidation(booleanRule)
        .setFormula('=if(and(not(isblank(A2)), not(isblank(C2)), isblank(D2)), true,)')
    spreadsheet.getSheetByName('Canonical Stories')
        .getRange('F2:F')
        .setDataValidation(incipitRule)
    spreadsheet.getSheetByName('Story Instances')
        .getRange('A2:A')
        .setDataValidation(manuscriptRule)
    spreadsheet.getSheetByName('Story Instances')
        .getRange('B2:B')
        .setDataValidation(canonicalStoryRule)
}
